#!/bin/bash

#Default location of shell
#If you are going to change this variable...
#Please make sure to change the variables in the Src/global.h file

DEFAULT_LOCATION="/etc/Restricted-Shell/"

#Define colors for color-coating output
RED_TEXT='\033[0;31m'
RESET='\033[0m'

